training_mode: False
enable_timing: False

batch_size: 64
threshold: 0.5

pipeline_steps:
  - point-net-outlier-detector
  - dlt-pose-solver
  - so3-matrix-projector

loss_weights:
  last-sv-loss: 0.0
  last-svs-ratio-loss: 0.0
  reprojection-loss: 0.0
  inlier-loss: 0.0
  supervised-inlier-loss: 1.0

image_dim: [ 1280, 960 ]
outlier_probability: 0.1
n_correspondences:   256
min_noise_std:       0.0
x_range:             40
y_range:             40
z_range:             40
n_map_features:      2000
n_trajectory_points: 10
n_frames:            64
max_noise_std:       4.0
max_n_samples:       8192
min_outlier_offset:  10.0
normalize:           True
visualize:           False

k_matrix:
  - [1066.67, 0.0, 640.0]
  - [0.0, 1066.67, 480.0]
  - [0.0, 0.0, 1.0]
