tag: synthetic
wandb_project_name: "outlier_network_synthetic"

enable_timing: False
training_mode: True
train_outlier_model: True
train_correction_model: False
load_outlier_model: False
load_correction_model: False

batch_size:    16
num_epochs:    1024
lr_start:      0.0001
lr_decay:      0.1
threshold:     0.5
log_batch_period: 32
save_model_epoch_period: 64

pipeline_steps:
  - change-keyframe
  - normalize-correspondences
  - point-net-outlier-detector
  - dlt-pose-solver
  - so3-matrix-projector
  - back-to-world-frame

loss_weights:
  last-sv-loss: 1.0
  last-svs-ratio-loss: 20.0
  reprojection-loss: 0.0
  inlier-loss: 5.0
  supervised-inlier-loss: 0.0

image_dim: [ 1280, 960 ]
outlier_probability: 0.8
n_correspondences:   256
min_noise_std:       0.0
x_range:             40
y_range:             40
z_range:             40
n_map_features:      2000
n_trajectory_points: 10
n_frames:            64
max_noise_std:       4.0
max_n_samples:       1024
min_outlier_offset:  10.0

k_matrix:
  - [1066.67, 0.0, 640.0]
  - [0.0, 1066.67, 480.0]
  - [0.0, 0.0, 1.0]