tag: synthetic
wandb_project_name: "correction_network_synthetic"

training_mode: True
enable_timing: False
train_outlier_model: False
train_correction_model: True
load_outlier_model: True
load_correction_model: False

batch_size: 16
num_epochs: 1024
lr_start: 0.0005
# lr_decay: 0.1
threshold: 0.5
log_batch_period: 32
save_model_epoch_period: 64

pipeline_steps:
  - change-keyframe
  - normalize-correspondences
  - point-net-outlier-detector
  - dlt-pose-solver
  - so3-matrix-projector
  - back-to-world-frame
  - pose-matrix-to-vector
  - kalman-filter
  - normalize-trajectory
  - lstm-correction
  - pose-vector-to-mat

loss_weights:
  kalman-correction-l2-loss: 0.0
  kalman-correction-mse-loss: 1.0
  last-sv-loss: 0.0
  last-svs-ratio-loss: 0.0
  reprojection-loss: 0.0
  inlier-loss: 0.0
  supervised-inlier-loss: 0.0

image_dim: [ 1280, 960 ]
outlier_probability: 0.1
n_correspondences:   256
min_noise_std:       0.0
x_range:             40
y_range:             40
z_range:             40
n_map_features:      2000
n_trajectory_points: 10
n_frames:            64
max_noise_std:       4.0
max_n_samples:       1024
min_outlier_offset:  10.0

k_matrix:
  - [1066.67, 0.0, 640.0]
  - [0.0, 1066.67, 480.0]
  - [0.0, 0.0, 1.0]